title: BuildSettingExtractor
email: info@jamesdempsey.net
description: >- # this means to ignore newlines until "url:"
   BuildSettingExtractor: The fastest way to extract Xcode build settings.
url: "https://buildsettingextractor.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/